# Generated by Django 5.1.6 on 2025-02-16 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow_requests', '0002_rename_created_at_borrowrequest_requested_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequest',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
