# Generated by Django 5.1.6 on 2025-02-10 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
