# Generated by Django 5.1.6 on 2025-02-19 14:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0006_remove_profile_phone_number_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_checked',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
