# Generated by Django 5.1.6 on 2025-02-21 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0007_profile_last_checked_alter_user_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/default.webp', null=True, upload_to='profile_pics/'),
        ),
    ]
